I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 305, in script
    n "Order secured. Dissent neutralized. Peace at 98.7%."
ValueError: incomplete format

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 305, in script
    n "Order secured. Dissent neutralized. Peace at 98.7%."
  File "C:\Users\7brit\OneDrive\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\7brit\OneDrive\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\7brit\OneDrive\Desktop\renpy-8.3.7-sdk\renpy\exports\sayexports.py", line 121, in say
    what = what % tag_quoting_dict
ValueError: incomplete format

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Divided Skies 1.0
Mon Apr 21 19:18:20 2025
