I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 80, in script
    if ending == "control":
  File "game/script.rpy", line 80, in <module>
    if ending == "control":
NameError: name 'ending' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 80, in script
    if ending == "control":
  File "C:\Users\7brit\OneDrive\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\7brit\OneDrive\Desktop\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\7brit\OneDrive\Desktop\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 80, in <module>
    if ending == "control":
NameError: name 'ending' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Divided Skies 1.0
Thu Apr 17 00:32:14 2025
